import paramiko
username = input("username:")
password = input("password:")
enable = input("enable")
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect("10.128.0.26", 22, username, password,allow_agent=False,look_for_keys=False)
#stdin, stdout, stderr = ssh.exec_command("show run")
#print(stdout)
sshf = ssh.invoke_shell()
output = sshf.recv(65535)
print(output)
sshf.send('enable\r\n')
sshf.send(enable +'\r\n')
output = sshf.recv(65535)
print(output)
sshf.send('terminal pager 0\r\n')
output = sshf.recv(65535)
print(output)
sshf.send('more system:running-config\r\n')
output = sshf.recv(65535)
print(output)
output = sshf.recv(65535)
print(output)

